### ISSUE TITLE
Updating to 0.3.3 causes error

### ISSUE THREAD

**Issue by DrPitre** [Ghawken/HomeKitLink-Siri#18]
**Describe the bug**
When updating to the latest commit (0.3.3) and loading the plugin into Indigo, the log shows this:

```
   Starting plugin "HomeKitLink Siri 0.3.3" (pid 93746)
   HomeKitLink Siri Error          Error in plugin execution InitializeMain:

  File "plugin.py", line 35, in <module>
type: No module named 'pyhap'

```

**Comment by DrPitre** [comment]
If I revert back to the previous commit (0.3.2), the plugin works fine.

**Comment by Ghawken** [comment]
There has been no change in that for sometime.  The commit’s details only show a copy of files changed and nothing to do with pyhap… (checking for a typo somewhere- which doesn’t exist)
I would presume is related to where/what you have downloaded….

**Comment by DrPitre** [comment]
Weird. Just tried it again this morning and it works. Sorry for the false alarm.
