### ISSUE TITLE
Multiple items per bridge - [Yes - 95 per bridge, and as many bridges as wanted]

### ISSUE THREAD

**Issue by durosity** [Ghawken/HomeKitLink-Siri#2]
Is it planned to have multiple items per bridge?  I currently have about 150 devices published to HK using about 10 HKB 'hubs' and it works perfectly.  Having a 1:1 relationship is gonna be pretty messy, not to mention impossible based on the 95 device limit.  

You did say you wanted things to make it less boring :D

**Comment by Ghawken** [comment]
Not sure I follow

Each HomeKitList-Siri Bridge can have up to 95 or so Indigo Devices published to it.  Each Bridge is a separate HomeKitLink (HKLS) Device - Bridge.  You can have as many Bridge devices with this limit as you want.

You could have 10 HKLS device bridges and go with the same setup you have.

There is no overall device limit - you could have 50 bridges and 95 devices each if so wished.  Haven’t said that multiple bridges probably add some overhead and other than ease of setup - not much else.  I wouldn’t be adding bridges for the fun of it…

Some other implementations have certain devices in their own standalone bridge - particularly Cameras.  I have dealt with this separately and the cameras don’t have any undue impact.  One thread only regardless of 1 or 21 cameras - multiple can slow down snapshot updates but that’s about it - won’t impact CPU.

**Comment by durosity** [comment]
Ah sorry sorry I misunderstood one of your instructions, I thought when you said that a particular device could only be added to one server at a time that meant only one device can be added to a bridge at a time!  Man I'm an idiot today!
