### ISSUE TITLE
Alarm integration

### ISSUE THREAD

**Issue by bla260** [Ghawken/HomeKitLink-Siri#20]
I am developer of Indigo ad2usb plugin and happy to explore feasibility of integration with HomeKit.

**Comment by Ghawken** [comment]
Ok.

The easiest (for me!) would be for your alarm plugin to have a state that reflects what HomeKit wants from its fairly simple alarm implementation.
& then a hidden action group that takes HomeKit states and converts this back to the ad2usb alarm state - changing modes.

(This is also the safest as your plugin is reporting states, not HomeKit Plugin trying to, and likewise action side of things)

This is what Joe is doing with the Alarm.com plugin - I believe…
https://github.com/FlyingDiver/Indigo-alarmdotcom/blob/main/AlarmDotCom.indigoPlugin/Contents/Server%20Plugin/Actions.xml
&
https://github.com/FlyingDiver/Indigo-Simplisafe

Although I have been away, so will add the HK side soon/next few days all going well.

HomeKit Alarm states are:
Simply these integers:

```
HK_ALARM_STAY_ARMED = 0
HK_ALARM_AWAY_ARMED = 1
HK_ALARM_NIGHT_ARMED = 2
HK_ALARM_DISARMED = 3
HK_ALARM_TRIGGERED = 4
```

So ideally add a custom state to ad2usb alarm state - “homeKitState”: and alter as above depending on what the alarm is doing.
&
Action group (can be hidden) as Joe above that the HomeKit plugin can action when a request to change state from HomeKit app is received.  Taking the above states as input and changing the mode as you see fit in your plugin.

**Comment by 7RDR7** [comment]
This one should be closed. BLA260 updated his plugin and I've been using it successfully with HKLS for months.

**Comment by Ghawken** [comment]
Will close.  Pretty sure had a number of private messages a while back to finalise the changes.
Thanks for pointing out.
