### ISSUE TITLE
Request - Door object

### ISSUE THREAD

**Issue by MKuchnic** [Ghawken/HomeKitLink-Siri#22]
The current version has a 0.4 has a window object type, but no Door object type.  Would it be possible to add it?
For your next enhancement list.

**Comment by Ghawken** [comment]
Hi
Already there to some extent I believe.

The contactSensor devices can be changed in HomeKit app to:
(These are True or False depending on whether opened or closed type devices)
Blinds
Contact Sensor
Door
Garage Door
or
Window

**Comment by MKuchnic** [comment]
Thanks for letting me know.

I assumed the new plugin was similar to the old one plug-in.

I went ahead and modified it to contact sensor and applied door in the home app and it works fine.

Thanks for your patience.
Mark
