### ISSUE TITLE
Support for motorised doors

### ISSUE THREAD

**Issue by durosity** [Ghawken/HomeKitLink-Siri#26]
Would it be possible to add a type for motorised door/gate?  I've recently added a motor to my gate and want it to show up properly in home.

**Comment by Ghawken** [comment]
Is there a motorised door HomeKit Device type?

**Comment by Ghawken** [comment]
Try 0.5.11
Adds Door type, which is very similar to Window Covering.  Should manage Dimmer device, and OnOff Relay device.

**Comment by durosity** [comment]
Thanks for adding that!  I've added the gate controller to HKL but despite it being a on/off relay it's showing in Home as a dimmer:

Here's the device listing from indigo

Script address : 192.168.1.97 r1
batteryLevel : None
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
description :
deviceTypeId : Relay
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState :
folderId : 171631128
globalProps : MetaProps : (dict)
com.GlennNZ.indigoplugin.HomeKitLink-Siri : (dict)
HomeKit_audioSelector : false (bool)
HomeKit_bridgeUniqueID : 762268 (integer)
HomeKit_deviceSensor : onOffState (string)
HomeKit_deviceSubtype : Door (string)
HomeKit_inverseSelector : false (bool)
HomeKit_publishDevice : true (bool)
HomeKit_tempSelector : false (bool)
homekit-name : Side Gate (string)
pro.sleepers.indigoplugin.8channel-relay : (dict)
NumZones : 1 (string)
PumpControlOn : false (bool)
address : 192.168.1.97 r1 (string)
channel : 1 (string)
hostname : 192.168.1.97 (string)
logActions : true (bool)
logChanges : true (bool)
port : 1234 (string)
id : 395279225
lastChanged : 2023-01-08 13:11:00
lastSuccessfulComm : 2023-01-08 13:11:00
ledStates : []
model : 8 Channel Network Relay Board
name : Garden - Side Gate
onState : False
ownerProps : pro.sleepers.indigoplugin.8channel-relay : (dict)
NumZones : 1 (string)
PumpControlOn : false (bool)
address : 192.168.1.97 r1 (string)
channel : 1 (string)
hostname : 192.168.1.97 (string)
logActions : true (bool)
logChanges : true (bool)
port : 1234 (string)
pluginId : pro.sleepers.indigoplugin.8channel-relay
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
onOffState : off (on/off bool)
pulseCount : 0 (integer)
pulseTimestamp : (string)
subModel : Relay
subType : Relay
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None

How it shows in the config window:

![image](https://user-images.githubusercontent.com/17961550/211201858-88ab69df-0257-45ae-be31-26903d1c62e1.jpeg)

How it shows in home

![image](https://user-images.githubusercontent.com/17961550/211201881-614b6372-4726-4219-aae0-1c25b5f56bb9.png)

I've tried removing it and re-adding it, and also deleted the Indigo device and re-created, but no joy.  Any thoughts?

**Comment by durosity** [comment]
Script                          address : 192.168.1.97 r1
batteryLevel : None
buttonConfiguredCount : 0
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : Relay
displayStateId : onOffState
displayStateImageSel : PowerOff
displayStateValRaw : False
displayStateValUi : off
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 171631128
globalProps : MetaProps : (dict)
     com.GlennNZ.indigoplugin.HomeKitLink-Siri : (dict)
          HomeKit_audioSelector : false (bool)
          HomeKit_bridgeUniqueID : 762268 (integer)
          HomeKit_deviceSensor : onOffState (string)
          HomeKit_deviceSubtype : Door (string)
          HomeKit_inverseSelector : false (bool)
          HomeKit_publishDevice : true (bool)
          HomeKit_tempSelector : false (bool)
          homekit-name : Side Gate (string)
     pro.sleepers.indigoplugin.8channel-relay : (dict)
          NumZones : 1 (string)
          PumpControlOn : false (bool)
          address : 192.168.1.97 r1 (string)
          channel : 1 (string)
          hostname : 192.168.1.97 (string)
          logActions : true (bool)
          logChanges : true (bool)
          port : 1234 (string)
id : 395279225
lastChanged : 2023-01-08 13:11:00
lastSuccessfulComm : 2023-01-08 13:11:00
ledStates : []
model : 8 Channel Network Relay Board
name : Garden - Side Gate
onState : False
ownerProps : pro.sleepers.indigoplugin.8channel-relay : (dict)
     NumZones : 1 (string)
     PumpControlOn : false (bool)
     address : 192.168.1.97 r1 (string)
     channel : 1 (string)
     hostname : 192.168.1.97 (string)
     logActions : true (bool)
     logChanges : true (bool)
     port : 1234 (string)
pluginId : pro.sleepers.indigoplugin.8channel-relay
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     onOffState : off (on/off bool)
     pulseCount : 0 (integer)
     pulseTimestamp :  (string)
subModel : Relay
subType : Relay
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : True
version : None

Here's the device definition from Indigo:

**Comment by Ghawken** [comment]
Thats the Homekit Door type.
Yeah that’s the HomeKit door subtype, with percentages of open.  Should work fine with fully open and fully closed turning on/off as needed.  If not a dimmer device then bits inbetween are ignored.
Not sure if can remove that aspect of the door, for this motorised door type

**Comment by durosity** [comment]
Ah, no worries!  I've been able to work around it!  Much appreciated!
