### ISSUE TITLE
Garage Door Opener opening…

### ISSUE THREAD

**Issue by Ghawken** [Ghawken/HomeKitLink-Siri#4]
On startup of HomeKit app.
Likely getter issue - Garage door remains Opening…

**Comment by DrPitre** [comment]
Yes, I'm seeing this too Glenn. Here's what I see in the logs:

`   HomeKitLink Siri Error          Error in setter callback
Traceback (most recent call last):
  File "plugin.py", line 1843, in Plugin_setter_callback
    indigo.device.turnOn(accessoryself.indigodeviceid)
TypeError: device "Left Garage Door" class type MultiIODevice is not compatible with action turnOn/turnOff/toggle/lock/unlock/open/close
`

**Comment by Ghawken** [comment]
Thanks - it was the last device I added support for - and obviously didn’t finish it.

Although - I think what you are seeing is a different error, altogether.

What is the device that you are trying to control?  If it doesn’t support turnOn/turnOff - then Garage Door controller, or Switch, or Lightbulb won’t work.

Can you post the print out of the python reference for the device?  
Right click device in Indigo that controlling - copy python reference and then in scripting shell print the reference.
Depending on the device - will probably need custom support.

**Comment by DrPitre** [comment]
`>>> print (indigo.devices[501156211]) # "Left Garage Door"
address : 50.50.7D
analogInputCount : 0
analogInputs : []
batteryLevel : None
binaryInputCount : 1
binaryInputs : [False]
binaryOutputCount : 1
binaryOutputs : [False]
buttonGroupCount : 1
configured : True
description : The left garage door
deviceTypeId : 
displayStateId : binaryOutputsAll
displayStateImageSel : PowerOff
displayStateValRaw : 0
displayStateValUi : 0
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 6587014
globalProps : MetaProps : (dict)
     com.GlennNZ.indigoplugin.HomeKitLink-Siri : (dict)
          HomeKit_audioSelector : false (bool)
          HomeKit_bridgeUniqueID : 735518 (integer)
          HomeKit_deviceSensor : binaryOutput1 (string)
          HomeKit_deviceSubtype : GarageDoor (string)
          HomeKit_publishDevice : true (bool)
          HomeKit_tempSelector : false (bool)
          homekit-name : Left Garage Door (string)
id : 501156211
lastChanged : 2022-05-05 08:43:37
lastSuccessfulComm : 2022-05-05 08:43:37
model : I/O-Linc Controller
name : Left Garage Door
ownerProps : emptyDict : (dict)
pluginId : 
pluginProps : emptyDict : (dict)
protocol : Insteon
remoteDisplay : True
sensorInputCount : 0
sensorInputs : []
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     binaryInput1 : off (on/off bool)
     binaryInput1.ui : open (string)
     binaryInputsAll : 0 (string)
     binaryOutput1 : off (on/off bool)
     binaryOutputsAll : 0 (string)
subModel : 
subType : 
supportsAllLightsOnOff : False
supportsAllOff : True
supportsStatusRequest : True
version : 65
`

**Comment by Ghawken** [comment]
What actual hardware device is it?  I’ll have to format that output to make sense of it… when back at PC

May need to have custom support for it - or use a Masquerade Relay device or Virtual device in place for usage.

Found with a better look:
 I/O-Linc Controller name

**Comment by DrPitre** [comment]
Yes, sorry. It's an Insteon GarageLinc controller.

**Comment by Ghawken** [comment]
Sounds like that should be supported as a GarageDoor….   Insteon never been available in this country (I believe) so hence supporting not easy.
Would have though would work as a Indigo Relay device…. Obviously not.

Could Masquerade it (and that may need to be answer for some cases)
But will have a look at Indigo base class and see if can add support

**Comment by DrPitre** [comment]
HomeKit Bridge did support this, so I know it's possible. Let me know how I can help provide any additional details.

**Comment by Ghawken** [comment]
Well - anything is possible - and indeed this version is far more open than previous (in that ANY sensor device can be supported)
But as said will have a look

For interests sake - how do you get Indigo to open Garage Door?
Action group - Binary Output?  Or something similar

**Comment by DrPitre** [comment]
It's actually built into Indigo. See the attached screenshot.

![Screen Shot 2022-05-05 at 8 14 06 PM](https://user-images.githubusercontent.com/719845/167051009-da6c9206-bcbf-428c-a7ed-e596335fc840.png)

**Comment by Ghawken** [comment]
Yep - saw it was a MultiIO device - not one I have.  But as it is Indigo - based on those principles I wrote - should try to support it natively.
Issue will be for Homekit - which binary output to activate….  Always 1 easy enough, but may not be ideal.

**Comment by DrPitre** [comment]
In the case of GarageLinc, it is always 1. I think the GarageLinc is a special case of the IOLinc which can handle more than one binary output control.

**Comment by Ghawken** [comment]
Great - that’ll make it easier

**Comment by Ghawken** [comment]
Try 0.2.24+ Latest Version
Hard to test - but think it will support above.

Although doesn't seem plain sailing for prior:
](https://github.com/indigodomo/HomeKit-Bridge/issues/121)

**Comment by DrPitre** [comment]
Just tried it, getting this: 

May 6, 2022 at 9:58:10 AM
   HomeKitLink Siri Error          Error in setter callback
Traceback (most recent call last):
  File "plugin.py", line 1867, in Plugin_setter_callback
    indigo.device.setBinaryOutput(accessoryself.indigodeviceid, index=1, value=True)
AttributeError: 'DeviceCmds' object has no attribute 'setBinaryOutput'

**Comment by Ghawken** [comment]
Thanks - i think that is a typo - quick fix coming
Yep - that error at least is fixed in 0.2.25 - should be there now.

I’m am trying to find a virtual device,or SDK to mimic a multiIOdevice to aid in this… no luck as yet.
Unfortunately can’t create Insteon devices easily for testing…

**Comment by DrPitre** [comment]
Thanks.I just installed the new version. Different error in the log:

   HomeKitLink Siri Error          Error in setter callback
Traceback (most recent call last):
  File "plugin.py", line 1867, in Plugin_setter_callback
    indigo.iodevice.setBinaryOutput(accessoryself.indigodeviceid, index=1, value=True)
plugin_base.PluginBase.InvalidParameter: output binary index out-of-range

**Comment by DrPitre** [comment]
Update: I changed index=1 to index=0 for both cases on lines 1867 and 1869, and it works!

**Comment by Ghawken** [comment]
Thanks will update and check the device update code as well (this is the bit that updates HomeKit all when device is changed in indigo)

Apparently this is a legacy device type that indigo has been thinking of deprecating in favour of relays.
 Just would take long to recode.  Hopefully will get garage working - any other iodevices will need to be virtual devices etc

**Comment by Ghawken** [comment]
Should be fixed in latest.  Also I believe I have fixed the opening… closing.. pending bit that was the issue I was seeing

**Comment by DrPitre** [comment]
Yep, just grabbed it. Nice work, Glenn. I've been running your plugin in a separate home from the HomeKit Bridge for testing. It's time to abandon HomeKit Bride, I think!
