### ISSUE TITLE
Server device can be created with no on/off controls

### ISSUE THREAD

**Issue by durosity** [Ghawken/HomeKitLink-Siri#8]
**Describe the bug**
Server device can be created with no on/off controls as per attached screenshot

**To Reproduce**
1: Create new server device
2: Exit Config window by clicking cancel without adding any devices to be published
3: Edit device and publish an device

**Expected behavior**
On/Off buttons should be available to turn server on/off

**Screenshots**
How it shows:
<img width="860" alt="Screenshot 2022-05-06 at 20 32 32" src="https://user-images.githubusercontent.com/17961550/167212400-19660d21-cd82-48ad-974c-54d6759337ee.png">

**Device Information**
batteryLevel : None
buttonGroupCount : 0
configured : True
description : 
deviceTypeId : homeKitBridgeDevice
displayStateId : Status
displayStateImageSel : PowerOn
displayStateValRaw : Operational
displayStateValUi : Operational
enabled : True
energyAccumBaseTime : None
energyAccumTimeDelta : None
energyAccumTotal : None
energyCurLevel : None
errorState : 
folderId : 0
globalProps : MetaProps : (dict)
     com.GlennNZ.indigoplugin.HomeKitLink-Siri : (dict)
          HomeKit_publishDevice_2 : true (bool)
          altName : Door (string)
          audioSelector : false (bool)
          bridgeUniqueID : 549226 (integer)
          deviceId : 1396191405 (string)
          deviceSensor : onOffState (string)
          deviceSubtype : GarageDoor (string)
          doorbellId :  (string)
          enablePublishFields : true (bool)
          isDeviceSelected : true (bool)
          selectdevice_or_AG : device (string)
          showALL : true (bool)
          showSubtypes : true (bool)
          tempSelector : false (bool)
id : 214445379
lastChanged : 2022-05-06 21:16:00
lastSuccessfulComm : 2022-05-06 21:16:00
model : HomeKitLink-Siri Bridge
name : Garage - HomeKitLink
ownerProps : com.GlennNZ.indigoplugin.HomeKitLink-Siri : (dict)
     HomeKit_publishDevice_2 : true (bool)
     altName : Door (string)
     audioSelector : false (bool)
     bridgeUniqueID : 549226 (integer)
     deviceId : 1396191405 (string)
     deviceSensor : onOffState (string)
     deviceSubtype : GarageDoor (string)
     doorbellId :  (string)
     enablePublishFields : true (bool)
     isDeviceSelected : true (bool)
     selectdevice_or_AG : device (string)
     showALL : true (bool)
     showSubtypes : true (bool)
     tempSelector : false (bool)
pluginId : com.GlennNZ.indigoplugin.HomeKitLink-Siri
pluginProps : emptyDict : (dict)
protocol : Plugin
remoteDisplay : True
sharedProps : com.indigodomo.indigoserver : (dict)
states : States : (dict)
     QRCode : <div><h1>HomeKitLink Siri</h1>
  <p>  Indigo Plugin: Scan this QR Code to add HomeKitLink Siri Bridge to HomeKit</p>
  <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKUAAAClAQAAAAAVUAB3AAABKElEQVR4nO2WMY6DMBBFP0rh0kfwTeBiSEbKxchNfARKFxGzf8yuYJeU+1GKTGGZR2F75n+PYS+i4kPfny4AOnsmWzFyiqyl2exBGnxon1I6Ijw4oI/PhO4Smovx10XU7qXitAcFbfmlYgbu4U/WBdS1Q7Al+ZeiBHSLKQHx5BYFLWGOVmz25Ts1nVIdfABcO2LaqrncLMz0fJiPnhdQt/vKKtY+Msl9NC01c9mk6pYIP0pV0eVWuPKEYLTi5hAtrX5Xt9TuWVdRzldmlcMhvzI6oumTy8NvNi1twWO3QmLYayyh232WC+V67Awq6i60CXVoezh6XkG3HpuC7ybYJZTnZEfH7kIltXujVCrENH+/jXji5D1CS9u7b/L2enoN/j89x4e+Pf0CTh2QlCBVm1oAAAAASUVORK5CYII=" width="600" height="600"></div> (string)
     Status : Operational (string)
     pincode : 084-99-439 (string)
     uniqueID : 549226 (string)
subModel : 
subType : 
supportsAllLightsOnOff : False
supportsAllOff : False
supportsStatusRequest : False
version : None

**If Camera Stream Related**
N/A

**Additional context**
N/A

**Comment by durosity** [comment]
Just to add the device works, just doesn't have the controls.

**Comment by Ghawken** [comment]
Yes that is expected behaviour.  It’s not a Relay device in Indigo, hence no On/Off controls - which don’t completely make sense.  This was a executive decision - about how the threading/asyncio code runs to some extent as well.

To disable the bridge and all aspects of it, use the enable/disable communication checkbox - this runs Indigos deviceStart and deviceStop which is more appropriate.  Also sticks after plugin restart.

**Comment by durosity** [comment]
Ah, understood.
